#! /bin/sh
### BEGIN INIT INFO
# Provides:          startupautopi
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: AutoPi starter
# Description:       AutoPi starter
### END INIT INFO

do_start () {
    /usr/bin/forever start /opt/AutoPi/index.js
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: startautopi [start|stop]" >&2
    exit 3
    ;;
esac

: