#!/bin/bash
echo ""
echo "We are going to install Auto Pi It will take a while"
echo ""
echo ""
sudo apt-get install git -y
cd /opt/ && sudo git clone https://github.com/jaretburkett/AutoPi.git
sudo chown -R pi:pi /opt/AutoPi/
cd /opt/AutoPi && sudo sh setup.sh